# Generated by Django 3.0.6 on 2020-05-15 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('principal', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=256)),
                ('college_image', models.ImageField(upload_to='college/')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('branch', models.CharField(max_length=25)),
                ('semester', models.IntegerField()),
                ('student_image', models.ImageField(upload_to='student/')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='College.College')),
            ],
        ),
    ]
